USE COMPANY
GO

CREATE VIEW VDEPT_BUDGET(DNAME, DNO, NO_EMP, SUM_SAL, AVG_SAL)
	AS SELECT DNAME, d.DNO, COUNT(e.DNO), SUM(e.SALARY), AVG(e.SALARY)
	FROM department d LEFT OUTER JOIN employee e
	ON e.DNO = d.DNO
	GROUP BY DNAME, d.DNO;